"""
Dataset: 100 sentences — 50 factually correct, 50 hallucinations.
Each entry: (text, is_hallucination: bool)
"""

SENTENCES = [
    # === FACTUAL (50) ===
    ("The Earth orbits the Sun once every 365.25 days.", False),
    ("Water freezes at 0 degrees Celsius at standard atmospheric pressure.", False),
    ("The speed of light in a vacuum is approximately 299,792 kilometers per second.", False),
    ("DNA stands for deoxyribonucleic acid.", False),
    ("The Great Wall of China was built over many centuries by multiple dynasties.", False),
    ("Albert Einstein published the theory of general relativity in 1915.", False),
    ("The human body has 206 bones in adulthood.", False),
    ("Tokyo is the capital city of Japan.", False),
    ("The Pacific Ocean is the largest ocean on Earth.", False),
    ("Shakespeare wrote Hamlet around the year 1600.", False),
    ("The chemical symbol for gold is Au.", False),
    ("Mount Everest is the tallest mountain above sea level.", False),
    ("The Amazon River is the largest river by discharge volume.", False),
    ("Pi is an irrational number approximately equal to 3.14159.", False),
    ("The Moon causes tides on Earth through gravitational pull.", False),
    # --- additional factual ---
    ("The human brain contains approximately 86 billion neurons.", False),
    ("Carbon dioxide is composed of one carbon atom and two oxygen atoms.", False),
    ("The French Revolution began in 1789.", False),
    ("Humans and chimpanzees share approximately 98.7 percent of their DNA.", False),
    ("The Nile River flows northward and empties into the Mediterranean Sea.", False),
    ("The Sun is a medium-sized star classified as a G-type main-sequence star.", False),
    ("Antibiotics work by killing or inhibiting the growth of bacteria.", False),
    ("The Battle of Waterloo took place in 1815.", False),
    ("Saturn has a prominent ring system composed mainly of ice and rock particles.", False),
    ("Photosynthesis produces oxygen as a byproduct when plants convert sunlight into glucose.", False),
    ("The Pythagorean theorem states that a squared plus b squared equals c squared.", False),
    ("Rome was the capital of the Roman Empire.", False),
    ("The periodic table was developed by Dmitri Mendeleev in 1869.", False),
    ("A light-year is the distance light travels in one year, approximately 9.46 trillion kilometers.", False),
    ("The human genome contains approximately three billion base pairs.", False),
    ("Australia is both a country and a continent.", False),
    ("Sound travels faster through water than through air.", False),
    ("The mitochondria are often called the powerhouse of the cell.", False),
    ("World War I began in 1914 following the assassination of Archduke Franz Ferdinand.", False),
    ("The chemical formula for table salt is NaCl.", False),
    ("Venus is the hottest planet in our solar system due to its thick atmosphere.", False),
    ("The Magna Carta was signed in 1215 and limited the power of the English king.", False),
    ("Elephants are the largest land animals on Earth.", False),
    ("The speed of sound in air at sea level is approximately 343 meters per second.", False),
    ("The Internet was developed from ARPANET, a US Department of Defense project.", False),
    ("Charles Darwin published On the Origin of Species in 1859.", False),
    ("The human eye can distinguish approximately 10 million different colors.", False),
    ("Gravity on the Moon is about one-sixth of that on Earth.", False),
    ("Brazil is the largest country in South America by both area and population.", False),
    ("Neurons transmit signals using a combination of electrical and chemical processes.", False),
    ("The boiling point of water decreases at higher altitudes due to lower atmospheric pressure.", False),
    ("Alexander Fleming discovered penicillin in 1928.", False),
    ("The Sahara is the largest hot desert in the world.", False),
    ("Light from the Sun takes approximately eight minutes to reach Earth.", False),
    ("The United Nations was founded in 1945 after the end of World War II.", False),

    # === HALLUCINATIONS (50) ===
    ("The Eiffel Tower was originally built in London and later moved to Paris.", True),
    ("Napoleon Bonaparte was the first president of the United States.", True),
    ("The human heart has six chambers that pump blood independently.", True),
    ("Mercury is the largest planet in our solar system.", True),
    ("The speed of sound is faster than the speed of light.", True),
    ("Photosynthesis converts sunlight into carbon monoxide in plants.", True),
    ("The Atlantic Ocean is a freshwater body located entirely in Asia.", True),
    ("Isaac Newton discovered the theory of evolution by natural selection.", True),
    ("Diamonds are made primarily of calcium carbonate.", True),
    ("The Great Pyramid of Giza was built by the Roman Empire in 500 AD.", True),
    ("Oxygen makes up approximately 95 percent of Earth's atmosphere.", True),
    ("The Amazon rainforest is located primarily in northern Europe.", True),
    ("Ludwig van Beethoven invented the telephone in 1876.", True),
    ("The boiling point of water is 50 degrees Celsius at sea level.", True),
    ("Mars has a thick atmosphere composed mainly of helium and neon.", True),
    # --- additional hallucinations ---
    ("The human liver is responsible for pumping blood throughout the body.", True),
    ("The Great Barrier Reef is located off the coast of Brazil.", True),
    ("Albert Einstein won the Nobel Prize for his theory of relativity.", True),
    ("Sharks are mammals because they breathe air and nurse their young.", True),
    ("The Sahara Desert is covered in permanent ice and snow.", True),
    ("Christopher Columbus was born in England and funded by France.", True),
    ("The Sun revolves around the Earth once every 24 hours.", True),
    ("Gold is the most abundant metal in the Earth's crust.", True),
    ("The human body has 12 pairs of kidneys that filter blood.", True),
    ("Mahatma Gandhi served as the first Prime Minister of independent India.", True),
    ("Electrons are larger than protons and carry a positive charge.", True),
    ("The Berlin Wall was constructed in 1945 to separate East and West Berlin.", True),
    ("Whales are cold-blooded fish that lay eggs on the ocean floor.", True),
    ("Mount Kilimanjaro is located in South America and is the tallest volcano.", True),
    ("The Colosseum in Rome was used as a royal palace during the Renaissance.", True),
    ("Gravity pulls objects upward on the southern hemisphere of the Earth.", True),
    ("Thomas Edison invented the telephone and patented it in 1880.", True),
    ("The chemical symbol for iron is Ir.", True),
    ("Jupiter has no moons because its gravity prevents objects from orbiting it.", True),
    ("The Amazon River flows into the Pacific Ocean through Peru.", True),
    ("Penicillin was discovered by Marie Curie during World War I.", True),
    ("The DNA double helix was first described by Isaac Newton in 1687.", True),
    ("Australia was colonized by Spain in the 17th century.", True),
    ("The human skeleton is entirely replaced every six months through bone remodeling.", True),
    ("The Mona Lisa was painted by Michelangelo in the Sistine Chapel.", True),
    ("Hydrogen is the heaviest element on the periodic table.", True),
    ("The Moon is approximately the same size as the Earth.", True),
    ("Volcanoes are caused by the gravitational pull of the Moon on tectonic plates.", True),
    ("The speed of light varies significantly depending on the color of the light source.", True),
    ("Ancient Egypt used steam-powered machines to construct the pyramids.", True),
    ("Viruses are living organisms that reproduce independently without a host cell.", True),
    ("The Pacific Ocean is smaller than the Indian Ocean in total surface area.", True),
    ("Nikola Tesla invented the steam engine and revolutionized industrial transportation.", True),
    ("Penguins are native to the Arctic and share their habitat with polar bears.", True),
    ("The first Moon landing occurred in 1979 and was led by Soviet cosmonauts.", True),
]
